name: container-platform-prod

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      PORT: "8080"
      STARTUP_DELAY_SECONDS: "${STARTUP_DELAY_SECONDS}"
    ports:
      - "${APP_PORT}:8080"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.52.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

volumes:
  prometheus-data:

